config/routes.rb
ShoppingPlatform::Application.routes.draw do
  resources :shop_addresses

  resources :shops

  resources :categories do
    resources :products
  end

  resources :product_items

  resources :products

  resources :users do
    get :goto_login, :on => :collection
  end

  get "home/index"
  root :to => 'home#index'

end

app/controllers/shop_addresses_controller.rb
class ShopAddressesController < ApplicationController
  # GET /shop_addresses
  # GET /shop_addresses.json
  def index
    @shop_addresses = ShopAddress.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @shop_addresses }
    end
  end

  # GET /shop_addresses/1
  # GET /shop_addresses/1.json
  def show
    @shop_address = ShopAddress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @shop_address }
    end
  end

  # GET /shop_addresses/new
  # GET /shop_addresses/new.json
  def new
    @shop_address = ShopAddress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @shop_address }
    end
  end

  # GET /shop_addresses/1/edit
  def edit
    @shop_address = ShopAddress.find(params[:id])
  end

  # POST /shop_addresses
  # POST /shop_addresses.json
  def create
    @shop_address = ShopAddress.new(params[:shop_address])

    respond_to do |format|
      if @shop_address.save
        format.html { redirect_to @shop_address, :notice => 'Shop address was successfully created.' }
        format.json { render :json => @shop_address, :status => :created, :location => @shop_address }
      else
        format.html { render :action => "new" }
        format.json { render :json => @shop_address.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shop_addresses/1
  # PUT /shop_addresses/1.json
  def update
    @shop_address = ShopAddress.find(params[:id])

    respond_to do |format|
      if @shop_address.update_attributes(params[:shop_address])
        format.html { redirect_to @shop_address, :notice => 'Shop address was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @shop_address.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_addresses/1
  # DELETE /shop_addresses/1.json
  def destroy
    @shop_address = ShopAddress.find(params[:id])
    @shop_address.destroy

    respond_to do |format|
      format.html { redirect_to shop_addresses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/shop_addresses_helper.rb
module ShopAddressesHelper
end

app/views/shop_addresses/_form.html.erb
<%= form_for(@shop_address) do |f| %>
  <% if @shop_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop_address.errors.count, "error") %> prohibited this shop_address from being saved:</h2>

      <ul>
      <% @shop_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :building_date %><br />
    <%= f.datetime_select :building_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shop_addresses/edit.html.erb
<h1>Editing shop_address</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop_address %> |
<%= link_to 'Back', shop_addresses_path %>

app/views/shop_addresses/index.html.erb
<h1>Listing shop_addresses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Street</th>
    <th>Zip</th>
    <th>City</th>
    <th>Building date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shop_addresses.each do |shop_address| %>
  <tr>
    <td><%= shop_address.name %></td>
    <td><%= shop_address.street %></td>
    <td><%= shop_address.zip %></td>
    <td><%= shop_address.city %></td>
    <td><%= shop_address.building_date %></td>
    <td><%= link_to 'Show', shop_address %></td>
    <td><%= link_to 'Edit', edit_shop_address_path(shop_address) %></td>
    <td><%= link_to 'Destroy', shop_address, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shop address', new_shop_address_path %>

app/views/shop_addresses/new.html.erb
<h1>New shop_address</h1>

<%= render 'form' %>

<%= link_to 'Back', shop_addresses_path %>

app/views/shop_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shop_address.name %>
</p>

<p>
  <b>Street:</b>
  <%= @shop_address.street %>
</p>

<p>
  <b>Zip:</b>
  <%= @shop_address.zip %>
</p>

<p>
  <b>City:</b>
  <%= @shop_address.city %>
</p>

<p>
  <b>Building date:</b>
  <%= @shop_address.building_date %>
</p>


<%= link_to 'Edit', edit_shop_address_path(@shop_address) %> |
<%= link_to 'Back', shop_addresses_path %>